[build-system]
requires = ["setuptools>=42", "pyyaml", "tqdm", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "edgeai-tidlrunner"
version = "11.2.1"
description = "Edge AI TIDL Runner"
authors = [
    { name = "Edge AI Development Team", email = "edgeai-dev@list.ti.com" }
]
readme = "README.md"
license = {file = "LICENSE.md"}
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Artificial Intelligence"
]
dependencies = [
    "cython",
    "pillow",
    "requests",
    "tqdm",
    "pyyaml",
    "pycocotools",
    "colorama",
    "munkres",
    "json_tricks",
    "wurlitzer",
    "xlsxwriter",
    "tabulate",
    "bs4",
    "openpyxl",
    "librosa",
    "soundfile",
    "scipy",
    "plyfile",
    "h5py",
    "numpy<2",
    "opencv-python-headless<5",
    "onnx==1.18.0",
    "protobuf<5",
    "tflite==2.18",
]

[project.urls]
"Homepage" = "https://github.com/TexasInstruments/edgeai-tidlrunner"
"Bug Reports" = "https://github.com/TexasInstruments/edgeai-tidlrunner/issues"
"Source" = "https://github.com/TexasInstruments/edgeai-tidlrunner"

[project.optional-dependencies]
pc = [
    "onnxsim==0.4.35", 
    "onnx-graphsurgeon==0.6.1",
    "nuscenes-devkit", ## nuscenes-devkit needs to be moved to main requirements after figuring out on how to install on evm
]

evm = [
]

dev = [
    "pytest",
    "black",
    "flake8",
    "mypy"
]

audio = [
    "librosa",
    "soundfile",
    "scipy",
    "pesq",
    "pystoi",
    "scikit-learn",
    "datasets",
]

[project.scripts]
# tidlrunner-tools-install = "edgeai_tidlrunner.download:main" # not required anymore as the recent onnx-graphsurgeon can be put into requirements
tidlrunner-cli = "edgeai_tidlrunner.main:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["edgeai_tidlrunner*"]

